// 20221218195321
// https://api.github.com/users/davenaeder/followers

export default [
  {
    login: 'jessehub',
    id: 42835,
    node_id: 'MDQ6VXNlcjQyODM1',
    avatar_url: 'https://avatars.githubusercontent.com/u/42835?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/jessehub',
    html_url: 'https://github.com/jessehub',
    followers_url: 'https://api.github.com/users/jessehub/followers',
    following_url:
      'https://api.github.com/users/jessehub/following{/other_user}',
    gists_url: 'https://api.github.com/users/jessehub/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/jessehub/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/jessehub/subscriptions',
    organizations_url: 'https://api.github.com/users/jessehub/orgs',
    repos_url: 'https://api.github.com/users/jessehub/repos',
    events_url: 'https://api.github.com/users/jessehub/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/jessehub/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'denen99',
    id: 128247,
    node_id: 'MDQ6VXNlcjEyODI0Nw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/128247?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/denen99',
    html_url: 'https://github.com/denen99',
    followers_url: 'https://api.github.com/users/denen99/followers',
    following_url:
      'https://api.github.com/users/denen99/following{/other_user}',
    gists_url: 'https://api.github.com/users/denen99/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/denen99/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/denen99/subscriptions',
    organizations_url: 'https://api.github.com/users/denen99/orgs',
    repos_url: 'https://api.github.com/users/denen99/repos',
    events_url: 'https://api.github.com/users/denen99/events{/privacy}',
    received_events_url: 'https://api.github.com/users/denen99/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'reduxdj',
    id: 322547,
    node_id: 'MDQ6VXNlcjMyMjU0Nw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/322547?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/reduxdj',
    html_url: 'https://github.com/reduxdj',
    followers_url: 'https://api.github.com/users/reduxdj/followers',
    following_url:
      'https://api.github.com/users/reduxdj/following{/other_user}',
    gists_url: 'https://api.github.com/users/reduxdj/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/reduxdj/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/reduxdj/subscriptions',
    organizations_url: 'https://api.github.com/users/reduxdj/orgs',
    repos_url: 'https://api.github.com/users/reduxdj/repos',
    events_url: 'https://api.github.com/users/reduxdj/events{/privacy}',
    received_events_url: 'https://api.github.com/users/reduxdj/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'zafarella',
    id: 660742,
    node_id: 'MDQ6VXNlcjY2MDc0Mg==',
    avatar_url: 'https://avatars.githubusercontent.com/u/660742?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/zafarella',
    html_url: 'https://github.com/zafarella',
    followers_url: 'https://api.github.com/users/zafarella/followers',
    following_url:
      'https://api.github.com/users/zafarella/following{/other_user}',
    gists_url: 'https://api.github.com/users/zafarella/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/zafarella/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/zafarella/subscriptions',
    organizations_url: 'https://api.github.com/users/zafarella/orgs',
    repos_url: 'https://api.github.com/users/zafarella/repos',
    events_url: 'https://api.github.com/users/zafarella/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/zafarella/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'joelibaceta',
    id: 864790,
    node_id: 'MDQ6VXNlcjg2NDc5MA==',
    avatar_url: 'https://avatars.githubusercontent.com/u/864790?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/joelibaceta',
    html_url: 'https://github.com/joelibaceta',
    followers_url: 'https://api.github.com/users/joelibaceta/followers',
    following_url:
      'https://api.github.com/users/joelibaceta/following{/other_user}',
    gists_url: 'https://api.github.com/users/joelibaceta/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/joelibaceta/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/joelibaceta/subscriptions',
    organizations_url: 'https://api.github.com/users/joelibaceta/orgs',
    repos_url: 'https://api.github.com/users/joelibaceta/repos',
    events_url: 'https://api.github.com/users/joelibaceta/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/joelibaceta/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'jsiragusa',
    id: 1468129,
    node_id: 'MDQ6VXNlcjE0NjgxMjk=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1468129?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/jsiragusa',
    html_url: 'https://github.com/jsiragusa',
    followers_url: 'https://api.github.com/users/jsiragusa/followers',
    following_url:
      'https://api.github.com/users/jsiragusa/following{/other_user}',
    gists_url: 'https://api.github.com/users/jsiragusa/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/jsiragusa/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/jsiragusa/subscriptions',
    organizations_url: 'https://api.github.com/users/jsiragusa/orgs',
    repos_url: 'https://api.github.com/users/jsiragusa/repos',
    events_url: 'https://api.github.com/users/jsiragusa/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/jsiragusa/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'joprice',
    id: 2175555,
    node_id: 'MDQ6VXNlcjIxNzU1NTU=',
    avatar_url: 'https://avatars.githubusercontent.com/u/2175555?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/joprice',
    html_url: 'https://github.com/joprice',
    followers_url: 'https://api.github.com/users/joprice/followers',
    following_url:
      'https://api.github.com/users/joprice/following{/other_user}',
    gists_url: 'https://api.github.com/users/joprice/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/joprice/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/joprice/subscriptions',
    organizations_url: 'https://api.github.com/users/joprice/orgs',
    repos_url: 'https://api.github.com/users/joprice/repos',
    events_url: 'https://api.github.com/users/joprice/events{/privacy}',
    received_events_url: 'https://api.github.com/users/joprice/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'anilwanted',
    id: 2373361,
    node_id: 'MDQ6VXNlcjIzNzMzNjE=',
    avatar_url: 'https://avatars.githubusercontent.com/u/2373361?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/anilwanted',
    html_url: 'https://github.com/anilwanted',
    followers_url: 'https://api.github.com/users/anilwanted/followers',
    following_url:
      'https://api.github.com/users/anilwanted/following{/other_user}',
    gists_url: 'https://api.github.com/users/anilwanted/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/anilwanted/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/anilwanted/subscriptions',
    organizations_url: 'https://api.github.com/users/anilwanted/orgs',
    repos_url: 'https://api.github.com/users/anilwanted/repos',
    events_url: 'https://api.github.com/users/anilwanted/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/anilwanted/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'mikegwhit',
    id: 2973130,
    node_id: 'MDQ6VXNlcjI5NzMxMzA=',
    avatar_url: 'https://avatars.githubusercontent.com/u/2973130?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mikegwhit',
    html_url: 'https://github.com/mikegwhit',
    followers_url: 'https://api.github.com/users/mikegwhit/followers',
    following_url:
      'https://api.github.com/users/mikegwhit/following{/other_user}',
    gists_url: 'https://api.github.com/users/mikegwhit/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/mikegwhit/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/mikegwhit/subscriptions',
    organizations_url: 'https://api.github.com/users/mikegwhit/orgs',
    repos_url: 'https://api.github.com/users/mikegwhit/repos',
    events_url: 'https://api.github.com/users/mikegwhit/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/mikegwhit/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'KevinHock',
    id: 3076393,
    node_id: 'MDQ6VXNlcjMwNzYzOTM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/3076393?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/KevinHock',
    html_url: 'https://github.com/KevinHock',
    followers_url: 'https://api.github.com/users/KevinHock/followers',
    following_url:
      'https://api.github.com/users/KevinHock/following{/other_user}',
    gists_url: 'https://api.github.com/users/KevinHock/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/KevinHock/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/KevinHock/subscriptions',
    organizations_url: 'https://api.github.com/users/KevinHock/orgs',
    repos_url: 'https://api.github.com/users/KevinHock/repos',
    events_url: 'https://api.github.com/users/KevinHock/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/KevinHock/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'VagrantStory',
    id: 4069972,
    node_id: 'MDQ6VXNlcjQwNjk5NzI=',
    avatar_url: 'https://avatars.githubusercontent.com/u/4069972?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/VagrantStory',
    html_url: 'https://github.com/VagrantStory',
    followers_url: 'https://api.github.com/users/VagrantStory/followers',
    following_url:
      'https://api.github.com/users/VagrantStory/following{/other_user}',
    gists_url: 'https://api.github.com/users/VagrantStory/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/VagrantStory/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/VagrantStory/subscriptions',
    organizations_url: 'https://api.github.com/users/VagrantStory/orgs',
    repos_url: 'https://api.github.com/users/VagrantStory/repos',
    events_url: 'https://api.github.com/users/VagrantStory/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/VagrantStory/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'attti',
    id: 4491248,
    node_id: 'MDQ6VXNlcjQ0OTEyNDg=',
    avatar_url: 'https://avatars.githubusercontent.com/u/4491248?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/attti',
    html_url: 'https://github.com/attti',
    followers_url: 'https://api.github.com/users/attti/followers',
    following_url: 'https://api.github.com/users/attti/following{/other_user}',
    gists_url: 'https://api.github.com/users/attti/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/attti/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/attti/subscriptions',
    organizations_url: 'https://api.github.com/users/attti/orgs',
    repos_url: 'https://api.github.com/users/attti/repos',
    events_url: 'https://api.github.com/users/attti/events{/privacy}',
    received_events_url: 'https://api.github.com/users/attti/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'AdibContractorCC',
    id: 5231789,
    node_id: 'MDQ6VXNlcjUyMzE3ODk=',
    avatar_url: 'https://avatars.githubusercontent.com/u/5231789?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/AdibContractorCC',
    html_url: 'https://github.com/AdibContractorCC',
    followers_url: 'https://api.github.com/users/AdibContractorCC/followers',
    following_url:
      'https://api.github.com/users/AdibContractorCC/following{/other_user}',
    gists_url: 'https://api.github.com/users/AdibContractorCC/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/AdibContractorCC/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/AdibContractorCC/subscriptions',
    organizations_url: 'https://api.github.com/users/AdibContractorCC/orgs',
    repos_url: 'https://api.github.com/users/AdibContractorCC/repos',
    events_url:
      'https://api.github.com/users/AdibContractorCC/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/AdibContractorCC/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'angusshire',
    id: 5877145,
    node_id: 'MDQ6VXNlcjU4NzcxNDU=',
    avatar_url: 'https://avatars.githubusercontent.com/u/5877145?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/angusshire',
    html_url: 'https://github.com/angusshire',
    followers_url: 'https://api.github.com/users/angusshire/followers',
    following_url:
      'https://api.github.com/users/angusshire/following{/other_user}',
    gists_url: 'https://api.github.com/users/angusshire/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/angusshire/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/angusshire/subscriptions',
    organizations_url: 'https://api.github.com/users/angusshire/orgs',
    repos_url: 'https://api.github.com/users/angusshire/repos',
    events_url: 'https://api.github.com/users/angusshire/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/angusshire/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'sarahmorrisokeefe',
    id: 6047067,
    node_id: 'MDQ6VXNlcjYwNDcwNjc=',
    avatar_url: 'https://avatars.githubusercontent.com/u/6047067?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/sarahmorrisokeefe',
    html_url: 'https://github.com/sarahmorrisokeefe',
    followers_url: 'https://api.github.com/users/sarahmorrisokeefe/followers',
    following_url:
      'https://api.github.com/users/sarahmorrisokeefe/following{/other_user}',
    gists_url: 'https://api.github.com/users/sarahmorrisokeefe/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/sarahmorrisokeefe/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/sarahmorrisokeefe/subscriptions',
    organizations_url: 'https://api.github.com/users/sarahmorrisokeefe/orgs',
    repos_url: 'https://api.github.com/users/sarahmorrisokeefe/repos',
    events_url:
      'https://api.github.com/users/sarahmorrisokeefe/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/sarahmorrisokeefe/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'MichalPaszkiewicz',
    id: 6673982,
    node_id: 'MDQ6VXNlcjY2NzM5ODI=',
    avatar_url: 'https://avatars.githubusercontent.com/u/6673982?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/MichalPaszkiewicz',
    html_url: 'https://github.com/MichalPaszkiewicz',
    followers_url: 'https://api.github.com/users/MichalPaszkiewicz/followers',
    following_url:
      'https://api.github.com/users/MichalPaszkiewicz/following{/other_user}',
    gists_url: 'https://api.github.com/users/MichalPaszkiewicz/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/MichalPaszkiewicz/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/MichalPaszkiewicz/subscriptions',
    organizations_url: 'https://api.github.com/users/MichalPaszkiewicz/orgs',
    repos_url: 'https://api.github.com/users/MichalPaszkiewicz/repos',
    events_url:
      'https://api.github.com/users/MichalPaszkiewicz/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/MichalPaszkiewicz/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'MCB-PRO-27',
    id: 6953104,
    node_id: 'MDQ6VXNlcjY5NTMxMDQ=',
    avatar_url: 'https://avatars.githubusercontent.com/u/6953104?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/MCB-PRO-27',
    html_url: 'https://github.com/MCB-PRO-27',
    followers_url: 'https://api.github.com/users/MCB-PRO-27/followers',
    following_url:
      'https://api.github.com/users/MCB-PRO-27/following{/other_user}',
    gists_url: 'https://api.github.com/users/MCB-PRO-27/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/MCB-PRO-27/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/MCB-PRO-27/subscriptions',
    organizations_url: 'https://api.github.com/users/MCB-PRO-27/orgs',
    repos_url: 'https://api.github.com/users/MCB-PRO-27/repos',
    events_url: 'https://api.github.com/users/MCB-PRO-27/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/MCB-PRO-27/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'miekapage',
    id: 29549344,
    node_id: 'MDQ6VXNlcjI5NTQ5MzQ0',
    avatar_url: 'https://avatars.githubusercontent.com/u/29549344?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/miekapage',
    html_url: 'https://github.com/miekapage',
    followers_url: 'https://api.github.com/users/miekapage/followers',
    following_url:
      'https://api.github.com/users/miekapage/following{/other_user}',
    gists_url: 'https://api.github.com/users/miekapage/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/miekapage/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/miekapage/subscriptions',
    organizations_url: 'https://api.github.com/users/miekapage/orgs',
    repos_url: 'https://api.github.com/users/miekapage/repos',
    events_url: 'https://api.github.com/users/miekapage/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/miekapage/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Jennabsol',
    id: 32465674,
    node_id: 'MDQ6VXNlcjMyNDY1Njc0',
    avatar_url: 'https://avatars.githubusercontent.com/u/32465674?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Jennabsol',
    html_url: 'https://github.com/Jennabsol',
    followers_url: 'https://api.github.com/users/Jennabsol/followers',
    following_url:
      'https://api.github.com/users/Jennabsol/following{/other_user}',
    gists_url: 'https://api.github.com/users/Jennabsol/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/Jennabsol/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Jennabsol/subscriptions',
    organizations_url: 'https://api.github.com/users/Jennabsol/orgs',
    repos_url: 'https://api.github.com/users/Jennabsol/repos',
    events_url: 'https://api.github.com/users/Jennabsol/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Jennabsol/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'jonassyon',
    id: 88140691,
    node_id: 'MDQ6VXNlcjg4MTQwNjkx',
    avatar_url: 'https://avatars.githubusercontent.com/u/88140691?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/jonassyon',
    html_url: 'https://github.com/jonassyon',
    followers_url: 'https://api.github.com/users/jonassyon/followers',
    following_url:
      'https://api.github.com/users/jonassyon/following{/other_user}',
    gists_url: 'https://api.github.com/users/jonassyon/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/jonassyon/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/jonassyon/subscriptions',
    organizations_url: 'https://api.github.com/users/jonassyon/orgs',
    repos_url: 'https://api.github.com/users/jonassyon/repos',
    events_url: 'https://api.github.com/users/jonassyon/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/jonassyon/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'JCSIVO',
    id: 104387283,
    node_id: 'U_kgDOBjjS0w',
    avatar_url: 'https://avatars.githubusercontent.com/u/104387283?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/JCSIVO',
    html_url: 'https://github.com/JCSIVO',
    followers_url: 'https://api.github.com/users/JCSIVO/followers',
    following_url: 'https://api.github.com/users/JCSIVO/following{/other_user}',
    gists_url: 'https://api.github.com/users/JCSIVO/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/JCSIVO/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/JCSIVO/subscriptions',
    organizations_url: 'https://api.github.com/users/JCSIVO/orgs',
    repos_url: 'https://api.github.com/users/JCSIVO/repos',
    events_url: 'https://api.github.com/users/JCSIVO/events{/privacy}',
    received_events_url: 'https://api.github.com/users/JCSIVO/received_events',
    type: 'User',
    site_admin: false,
  },
];
