export default {
  login: 'davenaeder',
  id: 67856,
  node_id: 'MDQ6VXNlcjY3ODU2',
  avatar_url: 'https://avatars.githubusercontent.com/u/67856?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/davenaeder',
  html_url: 'https://github.com/davenaeder',
  followers_url: 'https://api.github.com/users/davenaeder/followers',
  following_url:
    'https://api.github.com/users/davenaeder/following{/other_user}',
  gists_url: 'https://api.github.com/users/davenaeder/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/davenaeder/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/davenaeder/subscriptions',
  organizations_url: 'https://api.github.com/users/davenaeder/orgs',
  repos_url: 'https://api.github.com/users/davenaeder/repos',
  events_url: 'https://api.github.com/users/davenaeder/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/davenaeder/received_events',
  type: 'User',
  site_admin: false,
  name: 'David Naeder',
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 42,
  public_gists: 0,
  followers: 21,
  following: 27,
  created_at: '2009-03-27T14:31:20Z',
  updated_at: '2022-09-30T19:49:16Z',
};
